apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-26T17:17:02Z"
  labels:
    app: hello-app
  name: hello-app
  namespace: default
  resourceVersion: "75825"
  uid: 2377b5ab-cb40-44be-89ca-5b2eb27f7096
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.203.188
  clusterIPs:
  - 10.110.203.188
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31298
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
